fruits = ["apple", "banana"]
fruits.append("orange")
print(fruits)
fruits.insert(1,"grape")
print(fruits)
fruits.remove("banana")
print(fruits)
fruits.sort()
print(fruits)
fruits.reverse()
print(fruits)